config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :gexpenses do
      resources :member_expenses
    end
    resources :gcategories do
      resources :gitems
    end
    resources :activities do
      resources :schedules
    end
    resources :messages
    resources :memberships
  end
  
  post '/groups/:group_id/gexpenses/:gexpense_id/member_expenses/:id/pay' => 'member_expenses#pay', :as => 'pay_gexpenses'
  post '/groups/:group_id/gexpenses/:id/calc_shared' => 'gexpenses#calc_shared', :as => 'calc_shared'

  resources :profiles do
    resources :expenses
    resources :categories do
      resources :items
    end
  end
  
  get '/profiles/:profile_id/expenses_overview' => 'expenses#overview', :as => 'expenses_overview'

  get 'yourgroups' => 'groups#home', :as => 'group_home'
  get '/grouplist' => 'groups#search', :as => 'group_search'

  post '/groups/:group_id/join' => 'memberships#join', :as => 'join_membership'
  post '/groups/:group_id/memberships/:id/accept' => 'memberships#accept', :as => 'accept_membership'
  post '/groups/:group_id/memberships/:id/admin' => 'memberships#admin', :as => 'membership_admin'
  delete '/groups/:group_id/memberships/:id/leave' => 'memberships#leave', :as => 'membership_leave'

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  devise_for :users
  get 'welcome/index'
  
  get '/restricted' => 'welcome#restricted', :as => 'restricted'

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  # Many-To-Many rel with profiles(users) through memberships
  # A profile(user) can belong to many groups
  has_many :memberships, :dependent => :destroy
  has_many :profiles, :through => :memberships, :dependent => :destroy
  
  validates :name,
  :presence => true
  
  has_many :messages, :dependent => :destroy
  
  has_many :activities, :dependent => :destroy
  
  has_many :gexpenses, :dependent => :destroy
  
  has_many :gcategories, :dependent => :destroy
  
  def self.search(search)
    where("lower(name) LIKE ? OR lower(description) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
  end
end

app/controllers/gexpenses_controller.rb
class GexpensesController < ApplicationController
  before_action :set_gexpense, only: [:show, :edit, :update, :destroy]

  # GET /groups/:group_id/gexpenses
  def index
    @group = Group.find(params[:group_id])
    
    @gexpenses = @group.gexpenses
    
    @cat_exp = @gexpenses.group_by(&:category).sort
    
    @member_expense = MemberExpense.where(:gexpense_id => @gexpenses.ids)
  end

  # GET /groups/:group_id/gexpenses/:id
  def show
    @group = Group.find(params[:group_id])
    
    @gexpense = @group.gexpenses.find(params[:id])
    
    @member_expense = MemberExpense.where(:gexpense_id => @gexpense.id)
  end

  # GET /groups/:group_id/gexpenses/new
  def new
    @group = Group.find(params[:group_id])
    
    @gexpense = @group.gexpenses.build
    
    @membership = @group.memberships

    @gexpense.profile_id = current_user.id
    @gexpense.group_id = @group.id
    
    @gitem = Gitem.where(:gcategory_id => Gcategory.where(:group_id => (params[:group_id])))
  end

  # GET /groups/:group_id/gexpenses/:id/edit
  def edit
    @group = Group.find(params[:group_id])
    
    @gexpense = @group.gexpenses.find(params[:id])
    
    @membership = @group.memberships
    
    @gexpense.profile_id = current_user.id
    @gexpense.group_id = @group.id
    
    @gitem = Gitem.where(:gcategory_id => Gcategory.where(:group_id => (params[:group_id])))
  end

  # POST /groups/:group_id/gexpenses
  def create
    @group = Group.find(params[:group_id])
    
    @gexpense = @group.gexpenses.build(params.require(:gexpense).permit!)
    
    @membership = @group.memberships
    
    @gexpense.profile_id = current_user.id
    @gexpense.group_id = @group.id
    
    @gitem = Gitem.where(:gcategory_id => Gcategory.where(:group_id => (params[:group_id])))
    
    if @gexpense.save
      redirect_to group_gexpenses_url(@group)
    else
      render :action => "new"
    end
  end

  # PATCH/PUT /groups/:group_id/gexpenses/:id
  def update
    @group = Group.find(params[:group_id])
    @gexpense = Gexpense.find(params[:id])
    
    @membership = @group.memberships.where(:accepted_on.nil?)
    
    @gexpense.profile_id = current_user.id
    @gexpense.group_id = @group.id
    
    @gitem = Gitem.where(:gcategory_id => Gcategory.where(:group_id => (params[:group_id])))
    
    if @gexpense.update_attributes(params.require(:gexpense).permit!)
      redirect_to group_gexpenses_url(@group)
    else
      render :action => "edit"
    end
  end

  # DELETE /groups/:group_id/gexpenses/:id
  def destroy
    @group = Group.find(params[:group_id])
    @gexpense.destroy
    respond_to do |format|
      format.html { redirect_to group_gexpenses_url(@group), notice: 'Gexpense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def calc_shared
    @group = Group.find(params[:group_id])
    @gexpense = Gexpense.find(params[:id])
    
    @member_expense = @gexpense.member_expenses.count
    
    @shared_amt = @gexpense.total_amt / (@member_expense + 1)
    
    @gexpense.update_attribute(:shared_amt, @shared_amt)
    
    redirect_to request.referer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gexpense
      @gexpense = Gexpense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gexpense_params
      params.require(:gexpense).permit(:paid_on, :total_amt, :shared_amt, :profile_id, :group_id, :gitem_id, membership_ids:[])
    end
end

app/helpers/gexpenses_helper.rb
module GexpensesHelper
end

app/views/gexpenses/_form.html.erb
<%= form_for([@group, @gexpense]) do |f| %>
  <% if @gexpense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gexpense.errors.count, "error") %> prohibited this gexpense from being saved:</h2>

      <ul>
      <% @gexpense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paid_on %><br>
    <%= f.date_select :paid_on %>
  </div>
  <div class="field">
    <%= f.label 'Total Amount' %><br>
    <%= f.text_field :total_amt %>
  </div>
  <div class="field">
    <%= f.label 'Item' %><br>
    <%= f.select :gitem_id, @gitem.collect { |itm| [itm.itm_with_cat, itm.id] } %>
  </div>
  <div class="links">
    <p><%= link_to 'Create New Item', group_gcategories_path(@group, @gcategories) %></p>
  </div>
  <div class="clearfix"></div>
  <div class="field">
    <%= f.label 'Members Sharing this Expense (excluding yourself):' %>
    <%= f.collection_check_boxes :membership_ids, @membership.all, :id, :fname do |member| %>
      <div class="collection-check-box">
        <%= member.check_box %>
        <%= member.label %>
      </div>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gexpenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

app/views/gexpenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Group Categories</h1>

<div class="links">
  <p><%= link_to "+ Record New Expenses", new_group_gexpense_path(@group) %></p>
  <p><%= link_to "View All Categories", group_gcategories_path(@group) %></p>
</div>

<div class="clearfix"></div>

<% @cat_exp.each do |cat, expense| %>
  <h2><%= cat %></h2>
  
  <table>
    <thead>
      <tr>
        <th>Expense</th>
        <th>Contributor</th>
        <th>Total Amount</th>
        <th>Paid On</th>
        <th>Paid</th>
        <th>Owing</th>
        <th>Amount/person</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% expense.each do |e| %>
        <tr>
          <td><%= Gitem.find(e.gitem_id).name %></td>
          <td><%= Profile.find(e.profile_id).fname %></td>
          <td><%= e.total_amt %></td>
          <td><%= e.paid_on.strftime('%d %b %y') %></td>
          <td>
            <% @member_expense.where(:gexpense_id => e.id).each do |me| %>
              <% if me.paid %>
                <%= Profile.find(Membership.find(me.membership_id).profile_id).fname %> </br>
              <% end %>
            <% end %>
          </td>
          <td>
            <% @member_expense.where(:gexpense_id => e.id).each do |me| %>
              <% if me.paid %>
              <% else %>
                 <%= Profile.find(Membership.find(me.membership_id).profile_id).fname %>
                 <% if current_user.id == Membership.find(me.membership_id).profile_id %>
                   (<%= link_to 'Pay', pay_gexpenses_path(@group, e, me), method: :post, data: { confirm: 'By selecting this you are confirming that you have paid the contributor for the expense.' }%>)
                  <% end %>
                 </br>
              <% end %>
            <% end %>
          </td>
          <td>
            <% if e.shared_amt.nil? %>
              <%= link_to 'Calculate shared amount', calc_shared_path(@group, e), method: :post %>
            <% else %>
              <%= e.shared_amt %>
            <% end %>
          </td>
          <td>
            <% if current_user.id == e.profile_id %>
              <%= link_to 'Edit', edit_group_gexpense_path(@group, e) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  </br>
<% end %>

<%= link_to 'Back to Group', @group %>

app/views/gexpenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

app/views/gexpenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contributor:</strong>
  <%= Profile.find(@gexpense.profile_id).fname %>
</p>

<p>
  <strong>Paid on:</strong>
  <%= @gexpense.paid_on %>
</p>

<p>
  <strong>Category:</strong>
  <%= Gcategory.find(Gitem.find(@gexpense.gitem_id).gcategory_id).name %>
</p>

<p>
  <strong>Item:</strong>
  <%= Gitem.find(@gexpense.gitem_id).name %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @gexpense.total_amt %>
</p>

<p>
  <strong>Members sharing the Expense:</strong><br>
  <% @member_expense.each do |e| %>
    <%= Profile.find(Membership.find(e.membership_id)).fname %> </br>
  <% end %>
</p>

<p>
  <strong>Shared amount:</strong>
  <%= @gexpense.shared_amt %>
</p>


<%= link_to 'Edit', edit_group_gexpense_path(@group, @gexpense) %> |
<%= link_to 'Back', group_gexpenses_path(@group, @gexpense) %>