config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :gexpenses do
      resources :member_expenses
    end
    resources :gcategories do
      resources :gitems
    end
    resources :activities do
      resources :schedules
    end
    resources :messages
    resources :memberships
  end
  
  post '/groups/:group_id/gexpenses/:gexpense_id/member_expenses/:id/pay' => 'member_expenses#pay', :as => 'pay_gexpenses'
  post '/groups/:group_id/gexpenses/:id/calc_shared' => 'gexpenses#calc_shared', :as => 'calc_shared'

  resources :profiles do
    resources :expenses
    resources :categories do
      resources :items
    end
  end
  
  get '/profiles/:profile_id/expenses_overview' => 'expenses#overview', :as => 'expenses_overview'

  get 'yourgroups' => 'groups#home', :as => 'group_home'
  get '/grouplist' => 'groups#search', :as => 'group_search'

  post '/groups/:group_id/join' => 'memberships#join', :as => 'join_membership'
  post '/groups/:group_id/memberships/:id/accept' => 'memberships#accept', :as => 'accept_membership'
  post '/groups/:group_id/memberships/:id/admin' => 'memberships#admin', :as => 'membership_admin'
  delete '/groups/:group_id/memberships/:id/leave' => 'memberships#leave', :as => 'membership_leave'

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  devise_for :users
  get 'welcome/index'
  
  get '/restricted' => 'welcome#restricted', :as => 'restricted'

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  # Many-To-Many rel with profiles(users) through memberships
  # A profile(user) can belong to many groups
  has_many :memberships, :dependent => :destroy
  has_many :profiles, :through => :memberships, :dependent => :destroy
  
  validates :name,
  :presence => true
  
  has_many :messages, :dependent => :destroy
  
  has_many :activities, :dependent => :destroy
  
  has_many :gexpenses, :dependent => :destroy
  
  has_many :gcategories, :dependent => :destroy
  
  def self.search(search)
    where("lower(name) LIKE ? OR lower(description) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin, only: :index

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end
  
  # GET /groups/home
  def home
    # find the members with profile_id = current_user.id
    #@memberships = Membership.where(:profile_id => current_user.id)
    @memberships = Membership.all
    
    # access all groups that member brlongs to
    @groups = Group.all
  end
    
  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    
    # Check if current_user is admin
    @memberships = @group.memberships
    
    if @memberships.find_by_profile_id(current_user.id).nil?
      @admin = false
    else
      if @memberships.find_by_profile_id(current_user.id).g_admin == true
        @admin = true
      else
        @admin = false
      end
    end

    # Create a new message
    @message = @group.messages.build
    @message.profile_id = current_user.id
    @message.group_id = @group.id
    
    # List all messages for the group
    @messages = Message.all
    
    # List all activities
    @activities = Activity.all
    
    # List all schedules
    @schedules = Schedule.all
    
    # Group expenses details
    @gexpenses = @group.gexpenses

    @cat_exp = @gexpenses.group_by(&:category).sort
    @monthly_exp = @gexpenses.order('paid_on').group_by(&:month)

    @member_expense = MemberExpense.where(:gexpense_id => @gexpenses.ids)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        # Save creator (the user who created the group) as admin
        @group.memberships.create([ 
          { profile_id: current_user.id, accepted_on: Time.current, g_admin: true }
        ])
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # lists of groups for search
  def search
    @groups = Group.all
    if params[:search] 
      @groups = Group.search(params[:search]).order("name ASC")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

app/views/groups/home.html.erb
<div class="section">
    <div class="speech-bubble-bottom">
        <p>You can start managing your household activities by selecting on your group.</p>
        <p>To <i>join</i> a group, you can search by the group's name or description and request to join.</p>
        <p>You may also <i>create</i> a group and invite your housemates/flatmates to join you.</p>
        <p>Group functions like <b>Group Expenses</b>, <b>Group Schedules</b> and <b>Group Message Board</b> can only be accessed inside a group</p>
    </div>
    <img src="/assets/butler/butler2.png" alt="butler" title="Mr. Butler"/>
</div>

<div class="two-third">
    <div class="top">
        <div class="links">
            <p><%= link_to '+ Create Group', new_group_path %></p>
        </div>
        
        <div class="clearfix"></div>
        
        <div class="search">
            <%= form_tag(group_search_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search for a Group" %>
                <%= submit_tag "Search" %>
            <% end %>
        </div>
    </div>
    
    <div class="content">
        <h3>Your Groups</h3>
        <div class="round-border">
            <% if Membership.exists?(profile_id: current_user.id) %>
                <table>
                    <thead>
                        <tr>
                          <th>Name</th>
                          <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @memberships.where(:profile_id => current_user.id).each do |m| %>
                            <% @groups.where(:id => m.group_id).each do |g| %>
                                <% if m.accepted_on.nil? %>
                                 <% else %>
                                    <tr>
                                        <td><%= link_to g.name, g %></td>
                                        <td><%= g.description %></td>
                                    </tr>
                                <% end %>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            <% else %>
                <p>It seems that you do not belong to any groups. Please create a group or join a group.</p>
            <% end %>
        </div>
    </div>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Group ID</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

app/views/groups/search.html.erb
<h2>Listing Groups</h2>

<table>
    <thead>
        <tr>
            <th>Group Name</th>
            <th>Description</th>
            <th colspan ="1"></th>
        </tr>
    </thead>
    <tbody>
        <% @groups.each do |g| %>
            <tr>
                <td><%= g.name %></td>
                <td><%= g.description %></td>
                <% @memberships = Membership.where(:group_id => g.id) %>
                <% if @memberships.where(:profile_id => current_user.id).exists? %>
                    <td>&nbsp;</td>
                <% else %>
                    <td><%= link_to 'Join', join_membership_path(g.id, @membership), method: :post, data: { confirm: 'Request to join group?' } %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back', group_home_path %>

app/views/groups/show.html.erb
<div class="top">
  <div class="left">
    <h1><%= @group.name %></h1>
  </div>
  <div class="right">
    <div class="links">
      <p><%= link_to "View Members", group_memberships_path(@group) %></p>
      <% if @admin %>
        <p><%= link_to "Edit Group", edit_group_path(@group) %></p>
      <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<div class="section">
  <h2>Group Schedules</h2>
  <div class="create">
    <%= link_to "Create new Activity", new_group_activity_path(@group) %>
  </div>
  <div class="content">
    <% @activities.where(:group_id => @group).each do |act| %>
      <p><%= link_to act.name, group_activity_path(@group, act) %></p>
      <table>
        <tbody>
          <tr>
            <th>Date</th>
            <th>Start Time</th>
            <th>Person in Charge</th>
          </tr>
          <% @schedules.where(:activity_id => act).each do |sch| %>
            <tr>
              <td><%= sch.date.strftime("%e %b %y, %A") %></td>
              <td><%= sch.start_time.strftime("%H:%M") %></td>
              <% @membership = Membership.find(sch.membership_id) %>
              <td><%= Profile.find(@membership.profile_id).fname %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div class="section">
  <h2>Group Messages</h2>
  
  <!-- Box for posting a new message -->
  <%= form_for([@group, @message]) do |f| %>
    <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
  
        <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_field :content, :class => "message" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
    <br>
  <% end %>
  
  <!-- list all messages -->
  <div class="content">
    <% @messages.where(:group_id => @group).each do |msg| %>
      <table>
        <tbody>
          <% @profile = Profile.find(msg.profile_id) %>
          <tr>
            <th rowspan="2"><%= link_to image_tag(@profile.avatar.url(:mini)), profile_url(@profile) %></th>
            <th><%= @profile.fname %></th>
            <th colspan="2"><%= link_to 'Edit', edit_group_message_path(@group, msg) %> |
                            <%= link_to 'Destroy', group_message_path(@group, msg), method: :delete, data: { confirm: 'Are you sure?' } %></th>
          </tr>
          <tr>
            <th class="date"><%= msg.created_at.strftime("%A, %e %B %Y at %H:%M") %></th>
            <th>&nbsp;</th>
          </tr>
          <tr>
            <td colspan="5"><%= msg.content %></td>
          </tr>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>
</div>

<div class="section">
  <h2>Group Expenses</h2>
  <% if @gexpenses.nil? %>
  <% else %>
    <h3>Overview</h3>
    
    <div class="half">
      <table>
        <thead>
          <tr>
            <th>Month</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          <% @monthly_exp.each do |month, expenses| %>
            <tr>
              <td><%= month %></td>
              <% count_array = expenses.collect { |e| e.total_amt } %>
              <td><%= count_array.sum %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="half">
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          <% @cat_exp.each do |cat, expenses| %>
            <tr>
              <td><%= cat %></td>
              <% count_array = expenses.collect { |e| e.total_amt } %>
              <td><%= count_array.sum %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="clearfix"></div>
  <% end %>
  
  <div class="links">
    <p><%= link_to '+ Record a New Expense', new_group_gexpense_path(@group) %></p>
    <p><%= link_to 'View all Group Expenses', group_gexpenses_path(@group) %></p>
  </div>
  
  <% if @member_expense.where(:paid => false) %>
    <h3>Bills Outstanding</h3>
    
    <table>
      <thead>
        <tr>
          <th>Expense</th>
          <th>Date Incurred</th>
          <th>Owing</th>
          <th>Amount</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @member_expense.where(:paid => false).each do |e| %>
          <% if e.paid %>
          <% else %>
            <tr>
              <td><%= Gitem.find(Gexpense.find(e.gexpense_id).gitem_id).name %></td>
              <td><%= Gexpense.find(e.gexpense_id).paid_on.strftime('%d %b %y') %></td>
              <td><%= Profile.find(Membership.find(e.membership_id).profile_id).fname %></td>
              <td><%= Gexpense.find(e.gexpense_id).shared_amt %></td>
              <td>
                <% if current_user.id == Membership.find(e.membership_id).profile_id %>
                  (<%= link_to 'Pay', pay_gexpenses_path(@group, e.gexpense_id, e), method: :post, data: { confirm: 'By selecting this you are confirming that you have paid the contributor for the expense.' }%>)
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
  <p>All group expeneses have been paid!</p>
    
  <% end %>
</div>