config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :gexpenses do
      resources :member_expenses
    end
    resources :gcategories do
      resources :gitems
    end
    resources :activities do
      resources :schedules
    end
    resources :messages
    resources :memberships
  end
  
  post '/groups/:group_id/gexpenses/:gexpense_id/member_expenses/:id/pay' => 'member_expenses#pay', :as => 'pay_gexpenses'
  post '/groups/:group_id/gexpenses/:id/calc_shared' => 'gexpenses#calc_shared', :as => 'calc_shared'

  resources :profiles do
    resources :expenses
    resources :categories do
      resources :items
    end
  end
  
  get '/profiles/:profile_id/expenses_overview' => 'expenses#overview', :as => 'expenses_overview'

  get 'yourgroups' => 'groups#home', :as => 'group_home'
  get '/grouplist' => 'groups#search', :as => 'group_search'

  post '/groups/:group_id/join' => 'memberships#join', :as => 'join_membership'
  post '/groups/:group_id/memberships/:id/accept' => 'memberships#accept', :as => 'accept_membership'
  post '/groups/:group_id/memberships/:id/admin' => 'memberships#admin', :as => 'membership_admin'
  delete '/groups/:group_id/memberships/:id/leave' => 'memberships#leave', :as => 'membership_leave'

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  devise_for :users
  get 'welcome/index'
  
  get '/restricted' => 'welcome#restricted', :as => 'restricted'

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    belongs_to :profile
    has_many :items, :dependent => :destroy
    
    validates :name, :presence => true
    before_save :title_fields
    validates_uniqueness_of :name, :scope => :profile_id, :case_sensitive => false

    def title_fields
        self.name = self.name.titleize
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET profiles/:profile_id/categories
  def index
    @profile = Profile.find(params[:profile_id])
    
    @categories = @profile.categories
    
    @items = Item.all
  end

  # GET /profiles/:profile_id/categories/:id
  def show
    @profile = Profile.find(params[:profile_id])
    
    @category = @profile.categories.find(params[:id])
    
    @items = @category.items
  end

  # GET /profiles/:profile_id/categories/new
  def new
    @profile = Profile.find(params[:profile_id])
    
    @category = @profile.categories.build
    
    @category.profile_id = current_user.id
  end

  # GET /profiles/:profile_id/categories/:id/edit
  def edit
    @profile = Profile.find(params[:profile_id])
    
    @category = @profile.categories.find(params[:id])
  end

  # POST /profiles/:profile_id/categories
  def create
    @profile = Profile.find(params[:profile_id])
    
    @category = @profile.categories.build(params.require(:category).permit!)
    
    @category.profile_id = current_user.id
    
    if @category.save
      redirect_to profile_categories_url(@profile)
    else
      render :action => "new"
    end
  end

  # PATCH/PUT /profiles/:profile_id/categories/:id
  def update
    @profile = Profile.find(params[:profile_id])
    @category = Category.find(params[:id])
    
    if @category.update_attributes(params.require(:category).permit!)
      redirect_to profile_categories_url(@profile)
    else
      render :action => "edit"
    end
  end

  # DELETE /profiles/:profile_id/categories/:id
  def destroy
    @profile = Profile.find(params[:profile_id])
    @category.destroy
    
    respond_to do |format|
      format.html { redirect_to profile_categories_url(@profile), notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc, :profile_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for([@profile, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'description' %><br>
    <%= f.text_field :desc %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
  <div class="speech-bubble-bottom">
    <p>Remember, you will have to create a category before you can create an item.</p>
    <p>To add or view items of a category, simply click on the category.</p>
  </div>
    <img src="/assets/butler/butler3.png" alt="butler" title="Mr. Butler"/>
</div>
<div class="two-third">
  <h1>All Categories</h1>
  
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Description</th>
        <th>Items</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.name, profile_category_path(@profile, category) %></td>
          <td><%= category.desc %></td>
          <td>
            <% @items.where(:category_id => category.id).each do |itm| %>
              <%= itm.name %> <br>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_profile_category_path(@profile, category) %></td>
          <td><%= link_to 'Destroy', profile_category_path(@profile, category), method: :delete, data: { confirm: 'Are you sure? All items and expenses under this category will also be deleted.' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Category', new_profile_category_path(@profile) %> | 
  <%= link_to 'Back to Recording a New Expense', new_profile_expense_path(@profile) %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @category.name %></h1>

<p>
  <%= @category.desc %>
</p>

<p><%= link_to "+ add new item", new_profile_category_item_path(@profile, @category) %></p>
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Description</th>
      <th colspan="3">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |itm| %>
      <tr>
        <td><%= itm.name %></td>
        <td><%= itm.desc %></td>
        <td><%= link_to 'Edit', edit_profile_category_item_path(@profile, @category, itm) %></td>
        <td><%= link_to 'Destroy', profile_category_item_path(@profile, @category, itm), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</br>

<%= link_to 'Edit Category', edit_profile_category_path(@profile, @category) %> |
<%= link_to 'Back to Categories', profile_categories_path(@profile) %>