config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :gexpenses do
      resources :member_expenses
    end
    resources :gcategories do
      resources :gitems
    end
    resources :activities do
      resources :schedules
    end
    resources :messages
    resources :memberships
  end
  
  post '/groups/:group_id/gexpenses/:gexpense_id/member_expenses/:id/pay' => 'member_expenses#pay', :as => 'pay_gexpenses'
  post '/groups/:group_id/gexpenses/:id/calc_shared' => 'gexpenses#calc_shared', :as => 'calc_shared'

  resources :profiles do
    resources :expenses
    resources :categories do
      resources :items
    end
  end
  
  get '/profiles/:profile_id/expenses_overview' => 'expenses#overview', :as => 'expenses_overview'

  get 'yourgroups' => 'groups#home', :as => 'group_home'
  get '/grouplist' => 'groups#search', :as => 'group_search'

  post '/groups/:group_id/join' => 'memberships#join', :as => 'join_membership'
  post '/groups/:group_id/memberships/:id/accept' => 'memberships#accept', :as => 'accept_membership'
  post '/groups/:group_id/memberships/:id/admin' => 'memberships#admin', :as => 'membership_admin'
  delete '/groups/:group_id/memberships/:id/leave' => 'memberships#leave', :as => 'membership_leave'

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  devise_for :users
  get 'welcome/index'
  
  get '/restricted' => 'welcome#restricted', :as => 'restricted'

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :group
  
  has_many :schedules, :dependent => :destroy
  
  validates :name,
  :presence => true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /groups/:group_id/activities
  def index
    # For URL like /groups/1/activities
    # Get the group with id=1
    @group = Group.find(params[:group_id])
    
    # Access all activities for that group
    @activities = @group.activities
  end

  # GET /groups/:group_id/activities/:id
  def show
    @group = Group.find(params[:group_id])
    
    # For URL like /groups/1/activities/2
    # Find an activity in groups 1 that has id=2
    @activity = @group.activities.find(params[:id])
    
    # Access schedules
    @schedules = @activity.schedules
  end

  # GET /groups/:groups_id/activities/new
  def new
    @group = Group.find(params[:group_id])
    
    # Associate an activity object with group 1
    @activity = @group.activities.build
    
    @activity.group_id = @group.id
  end

  # GET /groups/:group_id/activities/:id/edit
  def edit
    @group = Group.find(params[:group_id])
    
    # For URL like /groups/1/activities/2/edit
    # Get activity id=2 for group 1
    @activity = @group.activities.find(params[:id])
  end

  # POST groups/:group_id/activities
  def create
    @group = Group.find(params[:group_id])
    
    # For URL like /groups/1/activites
    # Populate an activity association with group 1 with form data
    # Group will be associated with the activity
    @activity = @group.activities.build(params.require(:activity).permit!)
    
    @activity.group_id = @group.id

    if @activity.save
      # Save the activity successfully
      redirect_to group_url(@group)
    else
      render :action => "new"
    end
  end

  # PATCH/PUT /groups/:group_id/activities/:id
  def update
    @group = Group.find(params[:group_id])
    @activity = Activity.find(params[:id])
    
    if @activity.update_attributes(params.require(:activity).permit!)
      # Update the activity successfully
      redirect_to group_activity_url(@group, @activity)
    else
      render :action => "edit"
    end
  end

  # DELETE /groups/:group_id/activities/:id
  def destroy
    @group = Group.find(params[:group_id])
    @activity.destroy
    
    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'Activity was successfully destroyed.' }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :group_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for([@group, @activity]) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td><%= activity.group %></td>
        <td><%= link_to 'Show', group_activity_path(@group, activity) %></td>
        <td><%= link_to 'Edit', edit_group_activity_path(@group, activity) %></td>
        <td><%= link_to 'Destroy', group_activity_path(@group, activity), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_group_activity_path(@group) %> | 
<%= link_to 'Back to Group', group_path(@group) %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

app/views/activities/show.html.erb
<div class="section">
  <div class="speech-bubble-bottom">
    <p>Here is where you can add schedules to your group activities by specifying when a member of your group has to perform that activity.</p>
    <p>Unfortunately, for now, there is no options for recurring schedules so changes to dates and times has to be updated manually.</p>
  </div>
  
  <img src="/assets/butler/butler3.png" alt="butler" title="Mr. Butler"/>
</div>

<div class="two-third">
  <h1><%= @activity.name %></h1>
  <h3><%= @activity.description %></h3>
  
  <div class="links">
    <p><%= link_to "+ Add Schedule", new_group_activity_schedule_path(@group, @activity) %></p>
  </div>
  
  <div class="clearfix"></div>
  
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Start Time</th>
        <th>Person in Charge</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @schedules.each do |sch| %>
        <tr>
          <td><%= sch.date.strftime("%e %B %Y, %A") %></td>
          <td><%= sch.start_time.strftime("%H:%M") %></td>
          <% @membership = Membership.find(sch.membership_id) %>
          <td><%= Profile.find(@membership.profile_id).fname %></td>
          <td><%= link_to 'Edit', edit_group_activity_schedule_path(@group, @activity, sch) %> 
              <%= link_to 'Destroy', group_activity_schedule_path(@group, @activity, sch), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Edit Activity', edit_group_activity_path(@group, @activity) %> | 
<%= link_to 'Back to Group', @group %>